import crypto from "crypto";

// One-click email unsubscribe, verifiable without a database round trip or
// requiring the recipient to log in — the link just has to prove it was
// generated by this server for this exact user, not carry a secret that
// needs storing/expiring like the email-verification/password-reset tokens
// in authTokens.ts. An HMAC keyed on JWT_SECRET (already the one shared
// server-side secret, not exposed to the frontend) does that: recomputing it
// from the userId in the link and comparing is enough — no new secret to add
// to any .env file.
function sign(userId: string): string {
  return crypto.createHmac("sha256", process.env.JWT_SECRET as string).update(userId).digest("hex");
}

export function generateUnsubscribeToken(userId: string): string {
  return sign(userId);
}

export function verifyUnsubscribeToken(userId: string, token: string): boolean {
  const expected = sign(userId);
  // Constant-time compare — this is a verification check, same reasoning as
  // comparing a password hash, even though what's being protected here is
  // low-stakes (a marketing opt-out, not an account takeover).
  const a = Buffer.from(expected);
  const b = Buffer.from(token);
  return a.length === b.length && crypto.timingSafeEqual(a, b);
}
